# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FacebookAuth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FacebookAuth

  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'FacebookAuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FacebookAuth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FacebookAuth-tvOS

  target 'FacebookAuth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
